Repository askdebb/team3-Task-Planner-App, pull requests merged in 2024-05, with the labels that each got.

#5 Edited form fields labels and text
  index.html
Labels: duplicate, enhancement

#7 Task card layout
  .vscode/settings.json
  index.html
Labels: duplicate

#11 modify the task form
  index.html
Labels: enhancement

#12 capture the input value with JS
  index.html
  script.js
Labels: enhancement

#13 create array container to hold objects from the task form
  index.html
  script.js
Labels: enhancement

#28 I created the js file and the taskManager.js file in a js folder
  index.html
  js/index.js
  js/taskManager.js
Labels: enhancement

#29 Created a task manager class
  js/taskManager.js
Labels: enhancement

#15 Added a addTask function
  js/index.js
  js/taskManager.js
Labels: enhancement
